/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Swing;

/**
 *
 * @author pc
 */
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        adminIcon = new javax.swing.JLabel();
        adminDashBoard = new javax.swing.JButton();
        adminCourse = new javax.swing.JButton();
        adminTutors = new javax.swing.JButton();
        adminEdit = new javax.swing.JButton();
        adminLogOut = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        adminDashBoard3 = new javax.swing.JPanel();
        adminDashBoardTittle = new javax.swing.JLabel();
        adminDashBoardUserName = new javax.swing.JLabel();
        adminDashBoardRole = new javax.swing.JLabel();
        adminDaskBoardTotalStd1 = new javax.swing.JPanel();
        totalStd3 = new javax.swing.JLabel();
        stdValue3 = new javax.swing.JLabel();
        stdIcon3 = new javax.swing.JLabel();
        adminDashBoardTotalTeacher1 = new javax.swing.JPanel();
        totalTeacher3 = new javax.swing.JLabel();
        teacherValue3 = new javax.swing.JLabel();
        teacherIcon3 = new javax.swing.JLabel();
        adminDashBoardTotalCourse1 = new javax.swing.JPanel();
        totalCourse3 = new javax.swing.JLabel();
        courseValue3 = new javax.swing.JLabel();
        courseIcon3 = new javax.swing.JLabel();
        adminCourse3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        adminTutors3 = new javax.swing.JPanel();
        adminTutor3 = new javax.swing.JPanel();
        adminTutorName3 = new javax.swing.JLabel();
        adminTutorNameInput = new javax.swing.JTextField();
        adminTutorEmail3 = new javax.swing.JLabel();
        adminTutorEmailInput = new javax.swing.JTextField();
        adminTutorPhone = new javax.swing.JLabel();
        adminTutorCourse = new javax.swing.JLabel();
        adminTutorCourseInput = new javax.swing.JTextField();
        adminTutorPhoneInput = new javax.swing.JTextField();
        adminTutorAdd = new javax.swing.JButton();
        adminTutorDelect = new javax.swing.JButton();
        adminTutorUpdate = new javax.swing.JButton();
        adminTutorSave = new javax.swing.JButton();
        adminTutorsTable3 = new javax.swing.JScrollPane();
        tutorsTable3 = new javax.swing.JTable();
        adminEdit3 = new javax.swing.JPanel();
        adminEditTitle = new javax.swing.JLabel();
        adminEditIcon = new javax.swing.JLabel();
        adminEditFirstName = new javax.swing.JLabel();
        adminEditLastName = new javax.swing.JLabel();
        adminEditEmail = new javax.swing.JLabel();
        adminEditFirstNameUser = new javax.swing.JTextField();
        adminEditLastNameUser = new javax.swing.JTextField();
        adminEditPassword = new javax.swing.JLabel();
        adminEditEmailUser = new javax.swing.JTextField();
        adminEditPasswordUser = new javax.swing.JTextField();
        adminEditUserName = new javax.swing.JLabel();
        adminEditMobileNo = new javax.swing.JLabel();
        adminEditUserNameInput = new javax.swing.JTextField();
        adminEditMobileNoUser = new javax.swing.JTextField();
        adminEditBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Panel");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(247, 450));

        adminIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swing/icons8-student-64.png"))); // NOI18N
        adminIcon.setPreferredSize(new java.awt.Dimension(90, 50));

        adminDashBoard.setBackground(new java.awt.Color(107, 201, 46));
        adminDashBoard.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        adminDashBoard.setForeground(new java.awt.Color(255, 255, 255));
        adminDashBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swing/Rectangle 6.png"))); // NOI18N
        adminDashBoard.setText("DashBoard");
        adminDashBoard.setPreferredSize(new java.awt.Dimension(140, 40));
        adminDashBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminDashBoardActionPerformed(evt);
            }
        });

        adminCourse.setBackground(new java.awt.Color(107, 201, 46));
        adminCourse.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        adminCourse.setForeground(new java.awt.Color(255, 255, 255));
        adminCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swing/Rectangle 5.png"))); // NOI18N
        adminCourse.setText("Course");
        adminCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminCourseActionPerformed(evt);
            }
        });

        adminTutors.setBackground(new java.awt.Color(107, 201, 46));
        adminTutors.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        adminTutors.setForeground(new java.awt.Color(255, 255, 255));
        adminTutors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swing/Rectangle 4.png"))); // NOI18N
        adminTutors.setText("Tutors");
        adminTutors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminTutorsActionPerformed(evt);
            }
        });

        adminEdit.setBackground(new java.awt.Color(107, 201, 46));
        adminEdit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        adminEdit.setForeground(new java.awt.Color(255, 255, 255));
        adminEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swing/Rectangle 2.png"))); // NOI18N
        adminEdit.setText("Edit");
        adminEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminEditActionPerformed(evt);
            }
        });

        adminLogOut.setBackground(new java.awt.Color(107, 201, 46));
        adminLogOut.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        adminLogOut.setForeground(new java.awt.Color(255, 255, 255));
        adminLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swing/Rectangle 1.png"))); // NOI18N
        adminLogOut.setText("Log Out");
        adminLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminLogOutMouseClicked(evt);
            }
        });
        adminLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(adminDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(adminTutors, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adminEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adminLogOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adminCourse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(adminIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {adminCourse, adminDashBoard, adminEdit, adminLogOut, adminTutors});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(adminIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(adminDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(adminCourse)
                .addGap(10, 10, 10)
                .addComponent(adminTutors)
                .addGap(10, 10, 10)
                .addComponent(adminEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(adminLogOut)
                .addGap(36, 36, 36))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {adminCourse, adminDashBoard, adminEdit, adminLogOut, adminTutors});

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        adminDashBoard3.setBackground(new java.awt.Color(255, 255, 255));

        adminDashBoardTittle.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        adminDashBoardTittle.setForeground(new java.awt.Color(107, 201, 46));
        adminDashBoardTittle.setText("DashBoard");

        adminDashBoardUserName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        adminDashBoardUserName.setForeground(new java.awt.Color(107, 201, 46));
        adminDashBoardUserName.setText("Niraj");

        adminDashBoardRole.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        adminDashBoardRole.setForeground(new java.awt.Color(107, 201, 46));
        adminDashBoardRole.setText("student");

        adminDaskBoardTotalStd1.setBackground(new java.awt.Color(107, 201, 46));
        adminDaskBoardTotalStd1.setPreferredSize(new java.awt.Dimension(155, 130));

        totalStd3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        totalStd3.setForeground(new java.awt.Color(255, 255, 255));
        totalStd3.setText("Total Student");

        stdValue3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        stdValue3.setForeground(new java.awt.Color(255, 255, 255));
        stdValue3.setText("10");

        stdIcon3.setForeground(new java.awt.Color(255, 255, 255));
        stdIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swing/Rectangle 8.png"))); // NOI18N

        javax.swing.GroupLayout adminDaskBoardTotalStd1Layout = new javax.swing.GroupLayout(adminDaskBoardTotalStd1);
        adminDaskBoardTotalStd1.setLayout(adminDaskBoardTotalStd1Layout);
        adminDaskBoardTotalStd1Layout.setHorizontalGroup(
            adminDaskBoardTotalStd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminDaskBoardTotalStd1Layout.createSequentialGroup()
                .addGroup(adminDaskBoardTotalStd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminDaskBoardTotalStd1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(stdValue3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stdIcon3))
                    .addGroup(adminDaskBoardTotalStd1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(totalStd3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        adminDaskBoardTotalStd1Layout.setVerticalGroup(
            adminDaskBoardTotalStd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminDaskBoardTotalStd1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(totalStd3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adminDaskBoardTotalStd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdValue3)
                    .addComponent(stdIcon3))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        adminDashBoardTotalTeacher1.setBackground(new java.awt.Color(107, 201, 46));
        adminDashBoardTotalTeacher1.setPreferredSize(new java.awt.Dimension(155, 130));

        totalTeacher3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        totalTeacher3.setForeground(new java.awt.Color(255, 255, 255));
        totalTeacher3.setText("Total Teacher");

        teacherValue3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        teacherValue3.setForeground(new java.awt.Color(255, 255, 255));
        teacherValue3.setText("10");

        teacherIcon3.setForeground(new java.awt.Color(255, 255, 255));
        teacherIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swing/Rectangle 8.png"))); // NOI18N

        javax.swing.GroupLayout adminDashBoardTotalTeacher1Layout = new javax.swing.GroupLayout(adminDashBoardTotalTeacher1);
        adminDashBoardTotalTeacher1.setLayout(adminDashBoardTotalTeacher1Layout);
        adminDashBoardTotalTeacher1Layout.setHorizontalGroup(
            adminDashBoardTotalTeacher1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminDashBoardTotalTeacher1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(teacherValue3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teacherIcon3)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(adminDashBoardTotalTeacher1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalTeacher3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        adminDashBoardTotalTeacher1Layout.setVerticalGroup(
            adminDashBoardTotalTeacher1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminDashBoardTotalTeacher1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(totalTeacher3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adminDashBoardTotalTeacher1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teacherValue3)
                    .addComponent(teacherIcon3))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        adminDashBoardTotalCourse1.setBackground(new java.awt.Color(107, 201, 46));
        adminDashBoardTotalCourse1.setPreferredSize(new java.awt.Dimension(155, 130));

        totalCourse3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        totalCourse3.setForeground(new java.awt.Color(255, 255, 255));
        totalCourse3.setText("Total Course");

        courseValue3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        courseValue3.setForeground(new java.awt.Color(255, 255, 255));
        courseValue3.setText("10");

        courseIcon3.setForeground(new java.awt.Color(255, 255, 255));
        courseIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swing/Rectangle 8.png"))); // NOI18N

        javax.swing.GroupLayout adminDashBoardTotalCourse1Layout = new javax.swing.GroupLayout(adminDashBoardTotalCourse1);
        adminDashBoardTotalCourse1.setLayout(adminDashBoardTotalCourse1Layout);
        adminDashBoardTotalCourse1Layout.setHorizontalGroup(
            adminDashBoardTotalCourse1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminDashBoardTotalCourse1Layout.createSequentialGroup()
                .addGroup(adminDashBoardTotalCourse1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminDashBoardTotalCourse1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(courseValue3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(courseIcon3))
                    .addGroup(adminDashBoardTotalCourse1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(totalCourse3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        adminDashBoardTotalCourse1Layout.setVerticalGroup(
            adminDashBoardTotalCourse1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminDashBoardTotalCourse1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(totalCourse3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adminDashBoardTotalCourse1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(courseValue3)
                    .addComponent(courseIcon3))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout adminDashBoard3Layout = new javax.swing.GroupLayout(adminDashBoard3);
        adminDashBoard3.setLayout(adminDashBoard3Layout);
        adminDashBoard3Layout.setHorizontalGroup(
            adminDashBoard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminDashBoard3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(adminDashBoard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminDashBoard3Layout.createSequentialGroup()
                        .addComponent(adminDashBoardTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(adminDashBoard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(adminDashBoardRole)
                            .addComponent(adminDashBoardUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(adminDashBoard3Layout.createSequentialGroup()
                        .addComponent(adminDaskBoardTotalStd1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(adminDashBoardTotalTeacher1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                        .addGap(8, 8, 8)
                        .addComponent(adminDashBoardTotalCourse1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                        .addContainerGap(29, Short.MAX_VALUE))))
        );
        adminDashBoard3Layout.setVerticalGroup(
            adminDashBoard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminDashBoard3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(adminDashBoard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminDashBoardTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminDashBoardUserName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminDashBoardRole, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137)
                .addGroup(adminDashBoard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminDaskBoardTotalStd1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminDashBoardTotalTeacher1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminDashBoardTotalCourse1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(267, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", adminDashBoard3);

        adminCourse3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Course");

        javax.swing.GroupLayout adminCourse3Layout = new javax.swing.GroupLayout(adminCourse3);
        adminCourse3.setLayout(adminCourse3Layout);
        adminCourse3Layout.setHorizontalGroup(
            adminCourse3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminCourse3Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jLabel3)
                .addContainerGap(283, Short.MAX_VALUE))
        );
        adminCourse3Layout.setVerticalGroup(
            adminCourse3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminCourse3Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel3)
                .addContainerGap(446, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", adminCourse3);

        adminTutors3.setBackground(new java.awt.Color(255, 255, 255));

        adminTutor3.setBackground(new java.awt.Color(255, 255, 255));
        adminTutor3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tutor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(107, 201, 46))); // NOI18N
        adminTutor3.setForeground(new java.awt.Color(107, 201, 46));

        adminTutorName3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        adminTutorName3.setForeground(new java.awt.Color(107, 201, 46));
        adminTutorName3.setText("Name");

        adminTutorNameInput.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        adminTutorNameInput.setForeground(new java.awt.Color(107, 201, 46));
        adminTutorNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminTutorNameInputActionPerformed(evt);
            }
        });

        adminTutorEmail3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        adminTutorEmail3.setForeground(new java.awt.Color(107, 201, 46));
        adminTutorEmail3.setText("Email");

        adminTutorEmailInput.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        adminTutorEmailInput.setForeground(new java.awt.Color(107, 201, 46));
        adminTutorEmailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminTutorEmailInputActionPerformed(evt);
            }
        });

        adminTutorPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        adminTutorPhone.setForeground(new java.awt.Color(107, 201, 46));
        adminTutorPhone.setText("Phone");

        adminTutorCourse.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        adminTutorCourse.setForeground(new java.awt.Color(107, 201, 46));
        adminTutorCourse.setText("Course");

        adminTutorCourseInput.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        adminTutorCourseInput.setForeground(new java.awt.Color(107, 201, 46));
        adminTutorCourseInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminTutorCourseInputActionPerformed(evt);
            }
        });

        adminTutorPhoneInput.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        adminTutorPhoneInput.setForeground(new java.awt.Color(107, 201, 46));
        adminTutorPhoneInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminTutorPhoneInputActionPerformed(evt);
            }
        });

        adminTutorAdd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        adminTutorAdd.setForeground(new java.awt.Color(107, 201, 46));
        adminTutorAdd.setText("Add");

        adminTutorDelect.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        adminTutorDelect.setForeground(new java.awt.Color(107, 201, 46));
        adminTutorDelect.setText("Delete");

        adminTutorUpdate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        adminTutorUpdate.setForeground(new java.awt.Color(107, 201, 46));
        adminTutorUpdate.setText("Update");

        adminTutorSave.setText("Save");
        adminTutorSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminTutorSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminTutor3Layout = new javax.swing.GroupLayout(adminTutor3);
        adminTutor3.setLayout(adminTutor3Layout);
        adminTutor3Layout.setHorizontalGroup(
            adminTutor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminTutor3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(adminTutor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminTutor3Layout.createSequentialGroup()
                        .addComponent(adminTutorSave, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(adminTutor3Layout.createSequentialGroup()
                        .addGroup(adminTutor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(adminTutor3Layout.createSequentialGroup()
                                .addGroup(adminTutor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adminTutorNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adminTutorName3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adminTutorPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adminTutorPhoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(adminTutor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adminTutorEmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adminTutorEmail3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adminTutorCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adminTutorCourseInput, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminTutor3Layout.createSequentialGroup()
                                .addComponent(adminTutorAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(adminTutorDelect, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(adminTutorUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30))))
        );

        adminTutor3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {adminTutorEmailInput, adminTutorNameInput});

        adminTutor3Layout.setVerticalGroup(
            adminTutor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminTutor3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminTutor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminTutorName3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminTutorEmail3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(adminTutor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminTutorNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminTutorEmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adminTutor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminTutorCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminTutorPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(adminTutor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(adminTutorCourseInput, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(adminTutorPhoneInput))
                .addGap(20, 20, 20)
                .addGroup(adminTutor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminTutorAdd)
                    .addComponent(adminTutorDelect)
                    .addComponent(adminTutorUpdate))
                .addGap(18, 18, 18)
                .addComponent(adminTutorSave)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        adminTutor3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {adminTutorEmailInput, adminTutorNameInput});

        adminTutorsTable3.setBackground(new java.awt.Color(255, 255, 255));

        tutorsTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"saurabh chaudhary", "saurabha@gmail.com", "9812345678", "Bit"},
                {"ronit shreatha", "ronit@gmail.com", "98213456", "Bit"}
            },
            new String [] {
                "Name", "Email", "Phone", "Course"
            }
        ));
        adminTutorsTable3.setViewportView(tutorsTable3);

        javax.swing.GroupLayout adminTutors3Layout = new javax.swing.GroupLayout(adminTutors3);
        adminTutors3.setLayout(adminTutors3Layout);
        adminTutors3Layout.setHorizontalGroup(
            adminTutors3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminTutors3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(adminTutors3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(adminTutor3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adminTutorsTable3, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        adminTutors3Layout.setVerticalGroup(
            adminTutors3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminTutors3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminTutor3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adminTutorsTable3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        jTabbedPane1.addTab("tab3", adminTutors3);

        adminEdit3.setBackground(new java.awt.Color(255, 255, 255));

        adminEditTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        adminEditTitle.setForeground(new java.awt.Color(107, 201, 46));
        adminEditTitle.setText("Student Information");

        adminEditIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swing/icons8-student-registration-50.png"))); // NOI18N

        adminEditFirstName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        adminEditFirstName.setForeground(new java.awt.Color(107, 201, 46));
        adminEditFirstName.setText("FirstName");

        adminEditLastName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        adminEditLastName.setForeground(new java.awt.Color(107, 201, 46));
        adminEditLastName.setText("LastName");

        adminEditEmail.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        adminEditEmail.setForeground(new java.awt.Color(107, 201, 46));
        adminEditEmail.setText("Email");

        adminEditFirstNameUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        adminEditFirstNameUser.setForeground(new java.awt.Color(107, 201, 46));
        adminEditFirstNameUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        adminEditLastNameUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        adminEditLastNameUser.setForeground(new java.awt.Color(107, 201, 46));
        adminEditLastNameUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        adminEditPassword.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        adminEditPassword.setForeground(new java.awt.Color(107, 201, 46));
        adminEditPassword.setText("Password");

        adminEditEmailUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        adminEditEmailUser.setForeground(new java.awt.Color(107, 201, 46));
        adminEditEmailUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        adminEditPasswordUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        adminEditPasswordUser.setForeground(new java.awt.Color(107, 201, 46));
        adminEditPasswordUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        adminEditUserName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        adminEditUserName.setForeground(new java.awt.Color(107, 201, 46));
        adminEditUserName.setText("UserName");

        adminEditMobileNo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        adminEditMobileNo.setForeground(new java.awt.Color(107, 201, 46));
        adminEditMobileNo.setText("MobileNo");

        adminEditUserNameInput.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        adminEditUserNameInput.setForeground(new java.awt.Color(107, 201, 46));
        adminEditUserNameInput.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        adminEditUserNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminEditUserNameInputActionPerformed(evt);
            }
        });

        adminEditMobileNoUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        adminEditMobileNoUser.setForeground(new java.awt.Color(107, 201, 46));
        adminEditMobileNoUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        adminEditBtn.setBackground(new java.awt.Color(107, 201, 46));
        adminEditBtn.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        adminEditBtn.setForeground(new java.awt.Color(255, 255, 255));
        adminEditBtn.setText("Submit");
        adminEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminEditBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminEdit3Layout = new javax.swing.GroupLayout(adminEdit3);
        adminEdit3.setLayout(adminEdit3Layout);
        adminEdit3Layout.setHorizontalGroup(
            adminEdit3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminEdit3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(adminEdit3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminEdit3Layout.createSequentialGroup()
                        .addGroup(adminEdit3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(adminEdit3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(adminEditIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(adminEdit3Layout.createSequentialGroup()
                                .addComponent(adminEditFirstNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(40, 40, 40))
                    .addGroup(adminEdit3Layout.createSequentialGroup()
                        .addGroup(adminEdit3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminEditFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(adminEdit3Layout.createSequentialGroup()
                                .addGroup(adminEdit3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adminEditEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adminEditEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adminEditUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adminEditUserNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addGroup(adminEdit3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adminEditPasswordUser, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adminEditPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adminEditMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adminEditMobileNoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adminEditLastNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adminEditLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(adminEditTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(69, Short.MAX_VALUE))))
            .addGroup(adminEdit3Layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(adminEditBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        adminEdit3Layout.setVerticalGroup(
            adminEdit3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminEdit3Layout.createSequentialGroup()
                .addGroup(adminEdit3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminEdit3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(adminEditTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adminEdit3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(adminEditIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(adminEdit3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminEditFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminEditLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(adminEdit3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminEditFirstNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminEditLastNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(adminEdit3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminEditEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminEditPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(adminEdit3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminEditEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminEditPasswordUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(adminEdit3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminEditUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminEditMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(adminEdit3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminEditUserNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminEditMobileNoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(adminEditBtn)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", adminEdit3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, -40, -1, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adminLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLogOutActionPerformed
        // TODO add your handling code here:
adminLogOut.setBorderPainted(false);
    }//GEN-LAST:event_adminLogOutActionPerformed

    private void adminLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminLogOutMouseClicked
        // TODO add your handling code here:
        Login student = new Login();
        student.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_adminLogOutMouseClicked

    private void adminEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminEditActionPerformed
        // TODO add your handling code here
        adminEdit.setBorderPainted(false);
        jTabbedPane1.setSelectedIndex(3);
        
    }//GEN-LAST:event_adminEditActionPerformed

    private void adminTutorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminTutorsActionPerformed
        // TODO add your handling code here:
       adminTutors.setBorderPainted(false);
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_adminTutorsActionPerformed

    private void adminCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminCourseActionPerformed
        // TODO add your handling code here:
         adminCourse.setBorderPainted(false);
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_adminCourseActionPerformed

    private void adminDashBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminDashBoardActionPerformed
        // TODO add your handling code here:
        adminDashBoard.setBorderPainted(false);
        jTabbedPane1.setSelectedIndex(0);
        // studentDashBoard.setBorderPainted(false);
    }//GEN-LAST:event_adminDashBoardActionPerformed

    private void adminEditUserNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminEditUserNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminEditUserNameInputActionPerformed

    private void adminEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminEditBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminEditBtnActionPerformed

    private void adminTutorNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminTutorNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminTutorNameInputActionPerformed

    private void adminTutorEmailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminTutorEmailInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminTutorEmailInputActionPerformed

    private void adminTutorCourseInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminTutorCourseInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminTutorCourseInputActionPerformed

    private void adminTutorPhoneInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminTutorPhoneInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminTutorPhoneInputActionPerformed

    private void adminTutorSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminTutorSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminTutorSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminCourse;
    private javax.swing.JPanel adminCourse3;
    private javax.swing.JButton adminDashBoard;
    private javax.swing.JPanel adminDashBoard3;
    private javax.swing.JLabel adminDashBoardRole;
    private javax.swing.JLabel adminDashBoardTittle;
    private javax.swing.JPanel adminDashBoardTotalCourse1;
    private javax.swing.JPanel adminDashBoardTotalTeacher1;
    private javax.swing.JLabel adminDashBoardUserName;
    private javax.swing.JPanel adminDaskBoardTotalStd1;
    private javax.swing.JButton adminEdit;
    private javax.swing.JPanel adminEdit3;
    private javax.swing.JButton adminEditBtn;
    private javax.swing.JLabel adminEditEmail;
    private javax.swing.JTextField adminEditEmailUser;
    private javax.swing.JLabel adminEditFirstName;
    private javax.swing.JTextField adminEditFirstNameUser;
    private javax.swing.JLabel adminEditIcon;
    private javax.swing.JLabel adminEditLastName;
    private javax.swing.JTextField adminEditLastNameUser;
    private javax.swing.JLabel adminEditMobileNo;
    private javax.swing.JTextField adminEditMobileNoUser;
    private javax.swing.JLabel adminEditPassword;
    private javax.swing.JTextField adminEditPasswordUser;
    private javax.swing.JLabel adminEditTitle;
    private javax.swing.JLabel adminEditUserName;
    private javax.swing.JTextField adminEditUserNameInput;
    private javax.swing.JLabel adminIcon;
    private javax.swing.JButton adminLogOut;
    private javax.swing.JPanel adminTutor3;
    private javax.swing.JButton adminTutorAdd;
    private javax.swing.JLabel adminTutorCourse;
    private javax.swing.JTextField adminTutorCourseInput;
    private javax.swing.JButton adminTutorDelect;
    private javax.swing.JLabel adminTutorEmail3;
    private javax.swing.JTextField adminTutorEmailInput;
    private javax.swing.JLabel adminTutorName3;
    private javax.swing.JTextField adminTutorNameInput;
    private javax.swing.JLabel adminTutorPhone;
    private javax.swing.JTextField adminTutorPhoneInput;
    private javax.swing.JButton adminTutorSave;
    private javax.swing.JButton adminTutorUpdate;
    private javax.swing.JButton adminTutors;
    private javax.swing.JPanel adminTutors3;
    private javax.swing.JScrollPane adminTutorsTable3;
    private javax.swing.JLabel courseIcon3;
    private javax.swing.JLabel courseValue3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel stdIcon3;
    private javax.swing.JLabel stdValue3;
    private javax.swing.JLabel teacherIcon3;
    private javax.swing.JLabel teacherValue3;
    private javax.swing.JLabel totalCourse3;
    private javax.swing.JLabel totalStd3;
    private javax.swing.JLabel totalTeacher3;
    private javax.swing.JTable tutorsTable3;
    // End of variables declaration//GEN-END:variables
}
