/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Swing;

import com.sun.jdi.connect.spi.Connection;

import java.beans.Statement;
import java.util.Properties;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;



/**
 *
 * @author pc
 */
public class StudentPanel extends javax.swing.JFrame {

    
    

    /**
     * Creates new form StudentPanel
     */
    public StudentPanel() {
        initComponents();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        studentIcon = new javax.swing.JLabel();
        studentDashBoard = new javax.swing.JButton();
        studentCourse = new javax.swing.JButton();
        studentTutors = new javax.swing.JButton();
        studentEdit = new javax.swing.JButton();
        studentLogOut = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        studentDashBoard1 = new javax.swing.JPanel();
        stdDashBoardTotalTeacher1 = new javax.swing.JPanel();
        totalTeacher1 = new javax.swing.JLabel();
        teacherValue1 = new javax.swing.JLabel();
        teacherIcon1 = new javax.swing.JLabel();
        stdDashBoardTotalCourse1 = new javax.swing.JPanel();
        totalCourse1 = new javax.swing.JLabel();
        courseValue1 = new javax.swing.JLabel();
        courseIcon1 = new javax.swing.JLabel();
        stdDaskBoardTotalStd1 = new javax.swing.JPanel();
        totalStd1 = new javax.swing.JLabel();
        stdValue1 = new javax.swing.JLabel();
        stdIcon1 = new javax.swing.JLabel();
        studentDashBoardTittle = new javax.swing.JLabel();
        studentDashBoardUserName = new javax.swing.JLabel();
        studentDashBoardRole = new javax.swing.JLabel();
        studentCourse1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        studentTutors1 = new javax.swing.JPanel();
        studentTutorsTable1 = new javax.swing.JScrollPane();
        tutorsTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnView = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        studentEdit1 = new javax.swing.JPanel();
        stdEditFirstName = new javax.swing.JLabel();
        stdEditFirstNameUser = new javax.swing.JTextField();
        stdEditTitle = new javax.swing.JLabel();
        stdEditLastName = new javax.swing.JLabel();
        stdEditLastNameUser = new javax.swing.JTextField();
        stdEditEmail = new javax.swing.JLabel();
        stdEditEmailUser = new javax.swing.JTextField();
        stdEditPassword = new javax.swing.JLabel();
        stdEditPasswordUser = new javax.swing.JTextField();
        stdEditUserName = new javax.swing.JLabel();
        stdEditUserNameInput = new javax.swing.JTextField();
        stdEditMobileNo = new javax.swing.JLabel();
        stdEditMobileNoUser = new javax.swing.JTextField();
        stdEditBtn = new javax.swing.JButton();
        stdEditIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("StudentPanel");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(790, 620));
        setPreferredSize(new java.awt.Dimension(800, 610));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(247, 450));

        studentIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swing/icons8-student-64.png"))); // NOI18N
        studentIcon.setPreferredSize(new java.awt.Dimension(90, 50));

        studentDashBoard.setBackground(new java.awt.Color(107, 201, 46));
        studentDashBoard.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        studentDashBoard.setForeground(new java.awt.Color(255, 255, 255));
        studentDashBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swing/Rectangle 6.png"))); // NOI18N
        studentDashBoard.setText("DashBoard");
        studentDashBoard.setPreferredSize(new java.awt.Dimension(140, 40));
        studentDashBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentDashBoardActionPerformed(evt);
            }
        });

        studentCourse.setBackground(new java.awt.Color(107, 201, 46));
        studentCourse.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        studentCourse.setForeground(new java.awt.Color(255, 255, 255));
        studentCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swing/Rectangle 5.png"))); // NOI18N
        studentCourse.setText("Course");
        studentCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentCourseActionPerformed(evt);
            }
        });

        studentTutors.setBackground(new java.awt.Color(107, 201, 46));
        studentTutors.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        studentTutors.setForeground(new java.awt.Color(255, 255, 255));
        studentTutors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swing/Rectangle 4.png"))); // NOI18N
        studentTutors.setText("Tutors");
        studentTutors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentTutorsActionPerformed(evt);
            }
        });

        studentEdit.setBackground(new java.awt.Color(107, 201, 46));
        studentEdit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        studentEdit.setForeground(new java.awt.Color(255, 255, 255));
        studentEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swing/Rectangle 2.png"))); // NOI18N
        studentEdit.setText("Edit");
        studentEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentEditActionPerformed(evt);
            }
        });

        studentLogOut.setBackground(new java.awt.Color(107, 201, 46));
        studentLogOut.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        studentLogOut.setForeground(new java.awt.Color(255, 255, 255));
        studentLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swing/Rectangle 1.png"))); // NOI18N
        studentLogOut.setText("Log Out");
        studentLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentLogOutMouseClicked(evt);
            }
        });
        studentLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(studentDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(studentTutors, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(studentEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(studentLogOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(studentCourse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(studentIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {studentCourse, studentDashBoard, studentEdit, studentLogOut, studentTutors});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(studentIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(studentDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(studentCourse)
                .addGap(10, 10, 10)
                .addComponent(studentTutors)
                .addGap(10, 10, 10)
                .addComponent(studentEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(studentLogOut)
                .addGap(36, 36, 36))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {studentCourse, studentDashBoard, studentEdit, studentLogOut, studentTutors});

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        studentDashBoard1.setBackground(new java.awt.Color(255, 255, 255));
        studentDashBoard1.setPreferredSize(new java.awt.Dimension(565, 587));

        stdDashBoardTotalTeacher1.setBackground(new java.awt.Color(107, 201, 46));
        stdDashBoardTotalTeacher1.setPreferredSize(new java.awt.Dimension(155, 130));

        totalTeacher1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        totalTeacher1.setForeground(new java.awt.Color(255, 255, 255));
        totalTeacher1.setText("Total Teacher");

        teacherValue1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        teacherValue1.setForeground(new java.awt.Color(255, 255, 255));
        teacherValue1.setText("10");

        teacherIcon1.setForeground(new java.awt.Color(255, 255, 255));
        teacherIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swing/Rectangle 8.png"))); // NOI18N

        javax.swing.GroupLayout stdDashBoardTotalTeacher1Layout = new javax.swing.GroupLayout(stdDashBoardTotalTeacher1);
        stdDashBoardTotalTeacher1.setLayout(stdDashBoardTotalTeacher1Layout);
        stdDashBoardTotalTeacher1Layout.setHorizontalGroup(
            stdDashBoardTotalTeacher1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stdDashBoardTotalTeacher1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(teacherValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teacherIcon1)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(stdDashBoardTotalTeacher1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalTeacher1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        stdDashBoardTotalTeacher1Layout.setVerticalGroup(
            stdDashBoardTotalTeacher1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stdDashBoardTotalTeacher1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(totalTeacher1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(stdDashBoardTotalTeacher1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teacherValue1)
                    .addComponent(teacherIcon1))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        stdDashBoardTotalCourse1.setBackground(new java.awt.Color(107, 201, 46));
        stdDashBoardTotalCourse1.setPreferredSize(new java.awt.Dimension(155, 130));

        totalCourse1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        totalCourse1.setForeground(new java.awt.Color(255, 255, 255));
        totalCourse1.setText("Total Course");

        courseValue1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        courseValue1.setForeground(new java.awt.Color(255, 255, 255));
        courseValue1.setText("10");

        courseIcon1.setForeground(new java.awt.Color(255, 255, 255));
        courseIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swing/Rectangle 8.png"))); // NOI18N

        javax.swing.GroupLayout stdDashBoardTotalCourse1Layout = new javax.swing.GroupLayout(stdDashBoardTotalCourse1);
        stdDashBoardTotalCourse1.setLayout(stdDashBoardTotalCourse1Layout);
        stdDashBoardTotalCourse1Layout.setHorizontalGroup(
            stdDashBoardTotalCourse1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stdDashBoardTotalCourse1Layout.createSequentialGroup()
                .addGroup(stdDashBoardTotalCourse1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stdDashBoardTotalCourse1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(courseValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(courseIcon1))
                    .addGroup(stdDashBoardTotalCourse1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(totalCourse1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        stdDashBoardTotalCourse1Layout.setVerticalGroup(
            stdDashBoardTotalCourse1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stdDashBoardTotalCourse1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(totalCourse1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(stdDashBoardTotalCourse1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(courseValue1)
                    .addComponent(courseIcon1))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        stdDaskBoardTotalStd1.setBackground(new java.awt.Color(107, 201, 46));
        stdDaskBoardTotalStd1.setPreferredSize(new java.awt.Dimension(155, 130));

        totalStd1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        totalStd1.setForeground(new java.awt.Color(255, 255, 255));
        totalStd1.setText("Total Student");

        stdValue1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        stdValue1.setForeground(new java.awt.Color(255, 255, 255));
        stdValue1.setText("10");

        stdIcon1.setForeground(new java.awt.Color(255, 255, 255));
        stdIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swing/Rectangle 8.png"))); // NOI18N

        javax.swing.GroupLayout stdDaskBoardTotalStd1Layout = new javax.swing.GroupLayout(stdDaskBoardTotalStd1);
        stdDaskBoardTotalStd1.setLayout(stdDaskBoardTotalStd1Layout);
        stdDaskBoardTotalStd1Layout.setHorizontalGroup(
            stdDaskBoardTotalStd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stdDaskBoardTotalStd1Layout.createSequentialGroup()
                .addGroup(stdDaskBoardTotalStd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stdDaskBoardTotalStd1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(stdValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stdIcon1))
                    .addGroup(stdDaskBoardTotalStd1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(totalStd1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        stdDaskBoardTotalStd1Layout.setVerticalGroup(
            stdDaskBoardTotalStd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stdDaskBoardTotalStd1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(totalStd1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(stdDaskBoardTotalStd1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdValue1)
                    .addComponent(stdIcon1))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        studentDashBoardTittle.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        studentDashBoardTittle.setForeground(new java.awt.Color(107, 201, 46));
        studentDashBoardTittle.setText("DashBoard");

        studentDashBoardUserName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        studentDashBoardUserName.setForeground(new java.awt.Color(107, 201, 46));
        studentDashBoardUserName.setText("Niraj");

        studentDashBoardRole.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        studentDashBoardRole.setForeground(new java.awt.Color(107, 201, 46));
        studentDashBoardRole.setText("student");

        javax.swing.GroupLayout studentDashBoard1Layout = new javax.swing.GroupLayout(studentDashBoard1);
        studentDashBoard1.setLayout(studentDashBoard1Layout);
        studentDashBoard1Layout.setHorizontalGroup(
            studentDashBoard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentDashBoard1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(studentDashBoard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentDashBoard1Layout.createSequentialGroup()
                        .addComponent(studentDashBoardTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(studentDashBoard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(studentDashBoardRole)
                            .addComponent(studentDashBoardUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(studentDashBoard1Layout.createSequentialGroup()
                        .addComponent(stdDaskBoardTotalStd1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(stdDashBoardTotalTeacher1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                        .addGap(8, 8, 8)
                        .addComponent(stdDashBoardTotalCourse1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                        .addContainerGap(17, Short.MAX_VALUE))))
        );

        studentDashBoard1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {studentDashBoardRole, studentDashBoardUserName});

        studentDashBoard1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {stdDashBoardTotalCourse1, stdDashBoardTotalTeacher1, stdDaskBoardTotalStd1});

        studentDashBoard1Layout.setVerticalGroup(
            studentDashBoard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentDashBoard1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(studentDashBoard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentDashBoardTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentDashBoardUserName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentDashBoardRole, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137)
                .addGroup(studentDashBoard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stdDaskBoardTotalStd1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stdDashBoardTotalTeacher1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stdDashBoardTotalCourse1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(267, Short.MAX_VALUE))
        );

        studentDashBoard1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {studentDashBoardRole, studentDashBoardUserName});

        studentDashBoard1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {stdDashBoardTotalCourse1, stdDashBoardTotalTeacher1, stdDaskBoardTotalStd1});

        jTabbedPane1.addTab("tab1", studentDashBoard1);

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout studentCourse1Layout = new javax.swing.GroupLayout(studentCourse1);
        studentCourse1.setLayout(studentCourse1Layout);
        studentCourse1Layout.setHorizontalGroup(
            studentCourse1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentCourse1Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addGroup(studentCourse1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        studentCourse1Layout.setVerticalGroup(
            studentCourse1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentCourse1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jLabel1)
                .addContainerGap(324, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", studentCourse1);

        studentTutors1.setBackground(new java.awt.Color(255, 255, 255));

        studentTutorsTable1.setBackground(new java.awt.Color(255, 255, 255));

        tutorsTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"saurabh chaudhary", "saurabha@gmail.com", "9812345678", "Bit"},
                {"ronit shreatha", "ronit@gmail.com", "98213456", "Bit"}
            },
            new String [] {
                "Name", "Email", "Phone", "Course"
            }
        ));
        studentTutorsTable1.setViewportView(tutorsTable1);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Tutors");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        btnView.setText("View");

        btnClear.setText("Clear");

        javax.swing.GroupLayout studentTutors1Layout = new javax.swing.GroupLayout(studentTutors1);
        studentTutors1.setLayout(studentTutors1Layout);
        studentTutors1Layout.setHorizontalGroup(
            studentTutors1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentTutors1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(studentTutors1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentTutors1Layout.createSequentialGroup()
                        .addComponent(btnView)
                        .addGap(31, 31, 31)
                        .addComponent(btnClear))
                    .addGroup(studentTutors1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(studentTutorsTable1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(studentTutors1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        studentTutors1Layout.setVerticalGroup(
            studentTutors1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentTutors1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(studentTutors1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 24, Short.MAX_VALUE)
                .addGroup(studentTutors1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView)
                    .addComponent(btnClear))
                .addGap(18, 18, 18)
                .addComponent(studentTutorsTable1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        jTabbedPane1.addTab("tab3", studentTutors1);

        studentEdit1.setBackground(new java.awt.Color(255, 255, 255));
        studentEdit1.setPreferredSize(new java.awt.Dimension(530, 605));

        stdEditFirstName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        stdEditFirstName.setForeground(new java.awt.Color(107, 201, 46));
        stdEditFirstName.setText("FirstName");

        stdEditFirstNameUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        stdEditFirstNameUser.setForeground(new java.awt.Color(107, 201, 46));
        stdEditFirstNameUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        stdEditTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        stdEditTitle.setForeground(new java.awt.Color(107, 201, 46));
        stdEditTitle.setText("Student Information");

        stdEditLastName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        stdEditLastName.setForeground(new java.awt.Color(107, 201, 46));
        stdEditLastName.setText("LastName");

        stdEditLastNameUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        stdEditLastNameUser.setForeground(new java.awt.Color(107, 201, 46));
        stdEditLastNameUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        stdEditEmail.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        stdEditEmail.setForeground(new java.awt.Color(107, 201, 46));
        stdEditEmail.setText("Email");

        stdEditEmailUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        stdEditEmailUser.setForeground(new java.awt.Color(107, 201, 46));
        stdEditEmailUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        stdEditPassword.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        stdEditPassword.setForeground(new java.awt.Color(107, 201, 46));
        stdEditPassword.setText("Password");

        stdEditPasswordUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        stdEditPasswordUser.setForeground(new java.awt.Color(107, 201, 46));
        stdEditPasswordUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        stdEditUserName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        stdEditUserName.setForeground(new java.awt.Color(107, 201, 46));
        stdEditUserName.setText("UserName");

        stdEditUserNameInput.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        stdEditUserNameInput.setForeground(new java.awt.Color(107, 201, 46));
        stdEditUserNameInput.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        stdEditUserNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdEditUserNameInputActionPerformed(evt);
            }
        });

        stdEditMobileNo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        stdEditMobileNo.setForeground(new java.awt.Color(107, 201, 46));
        stdEditMobileNo.setText("MobileNo");

        stdEditMobileNoUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        stdEditMobileNoUser.setForeground(new java.awt.Color(107, 201, 46));
        stdEditMobileNoUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        stdEditBtn.setBackground(new java.awt.Color(107, 201, 46));
        stdEditBtn.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        stdEditBtn.setForeground(new java.awt.Color(255, 255, 255));
        stdEditBtn.setText("Submit");
        stdEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdEditBtnActionPerformed(evt);
            }
        });

        stdEditIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swing/icons8-student-registration-50.png"))); // NOI18N

        javax.swing.GroupLayout studentEdit1Layout = new javax.swing.GroupLayout(studentEdit1);
        studentEdit1.setLayout(studentEdit1Layout);
        studentEdit1Layout.setHorizontalGroup(
            studentEdit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentEdit1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(studentEdit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentEdit1Layout.createSequentialGroup()
                        .addComponent(stdEditTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stdEditIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(studentEdit1Layout.createSequentialGroup()
                        .addGroup(studentEdit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stdEditFirstNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stdEditFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(studentEdit1Layout.createSequentialGroup()
                                .addGroup(studentEdit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stdEditEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stdEditEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stdEditUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stdEditUserNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addGroup(studentEdit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stdEditPasswordUser, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stdEditPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stdEditMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stdEditMobileNoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stdEditLastNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stdEditLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(37, Short.MAX_VALUE))))
            .addGroup(studentEdit1Layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(stdEditBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        studentEdit1Layout.setVerticalGroup(
            studentEdit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentEdit1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(studentEdit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stdEditTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stdEditIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(studentEdit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdEditFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stdEditLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(studentEdit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdEditFirstNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stdEditLastNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(studentEdit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdEditEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stdEditPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(studentEdit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdEditEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stdEditPasswordUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(studentEdit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdEditUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stdEditMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(studentEdit1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdEditUserNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stdEditMobileNoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(stdEditBtn)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", studentEdit1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, -40, 540, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void studentDashBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentDashBoardActionPerformed
        // TODO add your handling code here:
          studentDashBoard.setBorderPainted(false); 
        jTabbedPane1.setSelectedIndex(0);
       // studentDashBoard.setBorderPainted(false);
        
    }//GEN-LAST:event_studentDashBoardActionPerformed

    private void studentCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentCourseActionPerformed
        // TODO add your handling code here:
         studentCourse.setBorderPainted(false); 
          jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_studentCourseActionPerformed

    private void studentTutorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentTutorsActionPerformed
        // TODO add your handling code here:
        studentTutors.setBorderPainted(false); 
          jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_studentTutorsActionPerformed

    private void studentEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentEditActionPerformed
        // TODO add your handling code here
         studentEdit.setBorderPainted(false);
          jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_studentEditActionPerformed

    private void studentLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentLogOutActionPerformed
        // TODO add your handling code here:
         studentLogOut.setBorderPainted(false);
        
    }//GEN-LAST:event_studentLogOutActionPerformed

    private void studentLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentLogOutMouseClicked
        // TODO add your handling code here:
        Login student = new Login();
        student.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_studentLogOutMouseClicked

    private void stdEditUserNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdEditUserNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdEditUserNameInputActionPerformed

    private void stdEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdEditBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdEditBtnActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased

        DefaultTableModel ob=(DefaultTableModel) tutorsTable1.getModel();
       TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(ob);
       tutorsTable1.setRowSorter(obj);
       obj.setRowFilter(RowFilter.regexFilter(jTextField1.getText()));
        
    }//GEN-LAST:event_jTextField1KeyReleased

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

//    
// 
//}
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel courseIcon1;
    private javax.swing.JLabel courseValue1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel stdDashBoardTotalCourse1;
    private javax.swing.JPanel stdDashBoardTotalTeacher1;
    private javax.swing.JPanel stdDaskBoardTotalStd1;
    private javax.swing.JButton stdEditBtn;
    private javax.swing.JLabel stdEditEmail;
    private javax.swing.JTextField stdEditEmailUser;
    private javax.swing.JLabel stdEditFirstName;
    private javax.swing.JTextField stdEditFirstNameUser;
    private javax.swing.JLabel stdEditIcon;
    private javax.swing.JLabel stdEditLastName;
    private javax.swing.JTextField stdEditLastNameUser;
    private javax.swing.JLabel stdEditMobileNo;
    private javax.swing.JTextField stdEditMobileNoUser;
    private javax.swing.JLabel stdEditPassword;
    private javax.swing.JTextField stdEditPasswordUser;
    private javax.swing.JLabel stdEditTitle;
    private javax.swing.JLabel stdEditUserName;
    private javax.swing.JTextField stdEditUserNameInput;
    private javax.swing.JLabel stdIcon1;
    private javax.swing.JLabel stdValue1;
    private javax.swing.JButton studentCourse;
    private javax.swing.JPanel studentCourse1;
    private javax.swing.JButton studentDashBoard;
    private javax.swing.JPanel studentDashBoard1;
    private javax.swing.JLabel studentDashBoardRole;
    private javax.swing.JLabel studentDashBoardTittle;
    private javax.swing.JLabel studentDashBoardUserName;
    private javax.swing.JButton studentEdit;
    private javax.swing.JPanel studentEdit1;
    private javax.swing.JLabel studentIcon;
    private javax.swing.JButton studentLogOut;
    private javax.swing.JButton studentTutors;
    private javax.swing.JPanel studentTutors1;
    private javax.swing.JScrollPane studentTutorsTable1;
    private javax.swing.JLabel teacherIcon1;
    private javax.swing.JLabel teacherValue1;
    private javax.swing.JLabel totalCourse1;
    private javax.swing.JLabel totalStd1;
    private javax.swing.JLabel totalTeacher1;
    private javax.swing.JTable tutorsTable1;
    // End of variables declaration//GEN-END:variables
}
