/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Swing;

/**
 *
 * @author pc
 */
public class TeacherPanel extends javax.swing.JFrame {

    /**
     * Creates new form TeacherPanel
     */
    public TeacherPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        teacherIcon = new javax.swing.JLabel();
        teacherCourse = new javax.swing.JButton();
        teacherTutors = new javax.swing.JButton();
        teacherEdit = new javax.swing.JButton();
        teacherLogOut = new javax.swing.JButton();
        teacherDashBoard = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        teacherDashboard2 = new javax.swing.JPanel();
        teacherDashBoardTittle = new javax.swing.JLabel();
        teacherDashBoardUserName = new javax.swing.JLabel();
        teacherDashBoardRole = new javax.swing.JLabel();
        teacherDaskBoardTotalStd2 = new javax.swing.JPanel();
        totalStd2 = new javax.swing.JLabel();
        stdValue2 = new javax.swing.JLabel();
        stdIcon2 = new javax.swing.JLabel();
        teacherDashBoardTotalTeacher2 = new javax.swing.JPanel();
        totalTeacher2 = new javax.swing.JLabel();
        teacherValue2 = new javax.swing.JLabel();
        teacherIcon2 = new javax.swing.JLabel();
        teacherDashBoardTotalCourse2 = new javax.swing.JPanel();
        totalCourse2 = new javax.swing.JLabel();
        courseValue2 = new javax.swing.JLabel();
        courseIcon2 = new javax.swing.JLabel();
        teacherCoourse2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        teacherTutors2 = new javax.swing.JPanel();
        teacherTutorsTable2 = new javax.swing.JScrollPane();
        tutorsTable2 = new javax.swing.JTable();
        teacherTutor2 = new javax.swing.JPanel();
        teacherTutorName2 = new javax.swing.JLabel();
        teacherTutorNameInput = new javax.swing.JTextField();
        teacherTutorEmail2 = new javax.swing.JLabel();
        teacherTutorEmailInput = new javax.swing.JTextField();
        teacherTutorPhone = new javax.swing.JLabel();
        teacherTutorCourse = new javax.swing.JLabel();
        teacherTutorCourseInput = new javax.swing.JTextField();
        teacherTutorPhoneInput = new javax.swing.JTextField();
        teacherTutorAdd = new javax.swing.JButton();
        teacherTutorDelect = new javax.swing.JButton();
        teacherTutorUpdate = new javax.swing.JButton();
        teacherTutorSave = new javax.swing.JButton();
        teacherEdit2 = new javax.swing.JPanel();
        teacherEditTitle = new javax.swing.JLabel();
        teacherEditIcon = new javax.swing.JLabel();
        teacherEditFirstName = new javax.swing.JLabel();
        teacherEditLastName = new javax.swing.JLabel();
        teacherEditFirstNameUser = new javax.swing.JTextField();
        teacherEditLastNameUser = new javax.swing.JTextField();
        teacherEditEmail = new javax.swing.JLabel();
        teacherEditPassword = new javax.swing.JLabel();
        teacherEditEmailUser = new javax.swing.JTextField();
        teacherEditPasswordUser = new javax.swing.JTextField();
        stdEditUserName = new javax.swing.JLabel();
        teacherEditMobileNo = new javax.swing.JLabel();
        teacherEditUserNameInput = new javax.swing.JTextField();
        teacherEditMobileNoUser = new javax.swing.JTextField();
        stdEditBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TeacherPanel");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 610));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(247, 450));

        teacherIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swing/icons8-course-100.png"))); // NOI18N
        teacherIcon.setPreferredSize(new java.awt.Dimension(90, 50));

        teacherCourse.setBackground(new java.awt.Color(107, 201, 46));
        teacherCourse.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        teacherCourse.setForeground(new java.awt.Color(255, 255, 255));
        teacherCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swing/Rectangle 5.png"))); // NOI18N
        teacherCourse.setText("Course");
        teacherCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherCourseActionPerformed(evt);
            }
        });

        teacherTutors.setBackground(new java.awt.Color(107, 201, 46));
        teacherTutors.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        teacherTutors.setForeground(new java.awt.Color(255, 255, 255));
        teacherTutors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swing/Rectangle 4.png"))); // NOI18N
        teacherTutors.setText("Tutors");
        teacherTutors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherTutorsActionPerformed(evt);
            }
        });

        teacherEdit.setBackground(new java.awt.Color(107, 201, 46));
        teacherEdit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        teacherEdit.setForeground(new java.awt.Color(255, 255, 255));
        teacherEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swing/Rectangle 2.png"))); // NOI18N
        teacherEdit.setText("Edit");
        teacherEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherEditActionPerformed(evt);
            }
        });

        teacherLogOut.setBackground(new java.awt.Color(107, 201, 46));
        teacherLogOut.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        teacherLogOut.setForeground(new java.awt.Color(255, 255, 255));
        teacherLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swing/Rectangle 1.png"))); // NOI18N
        teacherLogOut.setText("Log Out");
        teacherLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacherLogOutMouseClicked(evt);
            }
        });
        teacherLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherLogOutActionPerformed(evt);
            }
        });

        teacherDashBoard.setBackground(new java.awt.Color(107, 201, 46));
        teacherDashBoard.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        teacherDashBoard.setForeground(new java.awt.Color(255, 255, 255));
        teacherDashBoard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swing/Rectangle 6.png"))); // NOI18N
        teacherDashBoard.setText("DashBoard");
        teacherDashBoard.setPreferredSize(new java.awt.Dimension(140, 40));
        teacherDashBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherDashBoardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(teacherIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teacherLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherTutors, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {teacherCourse, teacherDashBoard, teacherEdit, teacherTutors});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(teacherIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(teacherDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(teacherCourse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(teacherTutors)
                .addGap(18, 18, 18)
                .addComponent(teacherEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(teacherLogOut)
                .addGap(54, 54, 54))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {teacherCourse, teacherDashBoard, teacherEdit, teacherTutors});

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        teacherDashboard2.setBackground(new java.awt.Color(255, 255, 255));

        teacherDashBoardTittle.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        teacherDashBoardTittle.setForeground(new java.awt.Color(107, 201, 46));
        teacherDashBoardTittle.setText("DashBoard");

        teacherDashBoardUserName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        teacherDashBoardUserName.setForeground(new java.awt.Color(107, 201, 46));
        teacherDashBoardUserName.setText("Niraj");

        teacherDashBoardRole.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        teacherDashBoardRole.setForeground(new java.awt.Color(107, 201, 46));
        teacherDashBoardRole.setText("student");

        teacherDaskBoardTotalStd2.setBackground(new java.awt.Color(107, 201, 46));
        teacherDaskBoardTotalStd2.setPreferredSize(new java.awt.Dimension(155, 130));

        totalStd2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        totalStd2.setForeground(new java.awt.Color(255, 255, 255));
        totalStd2.setText("Total Student");

        stdValue2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        stdValue2.setForeground(new java.awt.Color(255, 255, 255));
        stdValue2.setText("10");

        stdIcon2.setForeground(new java.awt.Color(255, 255, 255));
        stdIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swing/Rectangle 8.png"))); // NOI18N

        javax.swing.GroupLayout teacherDaskBoardTotalStd2Layout = new javax.swing.GroupLayout(teacherDaskBoardTotalStd2);
        teacherDaskBoardTotalStd2.setLayout(teacherDaskBoardTotalStd2Layout);
        teacherDaskBoardTotalStd2Layout.setHorizontalGroup(
            teacherDaskBoardTotalStd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherDaskBoardTotalStd2Layout.createSequentialGroup()
                .addGroup(teacherDaskBoardTotalStd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(teacherDaskBoardTotalStd2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(stdValue2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stdIcon2))
                    .addGroup(teacherDaskBoardTotalStd2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(totalStd2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        teacherDaskBoardTotalStd2Layout.setVerticalGroup(
            teacherDaskBoardTotalStd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherDaskBoardTotalStd2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(totalStd2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(teacherDaskBoardTotalStd2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdValue2)
                    .addComponent(stdIcon2))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        teacherDashBoardTotalTeacher2.setBackground(new java.awt.Color(107, 201, 46));
        teacherDashBoardTotalTeacher2.setPreferredSize(new java.awt.Dimension(155, 130));

        totalTeacher2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        totalTeacher2.setForeground(new java.awt.Color(255, 255, 255));
        totalTeacher2.setText("Total Instructor");

        teacherValue2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        teacherValue2.setForeground(new java.awt.Color(255, 255, 255));
        teacherValue2.setText("10");

        teacherIcon2.setForeground(new java.awt.Color(255, 255, 255));
        teacherIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swing/Rectangle 8.png"))); // NOI18N

        javax.swing.GroupLayout teacherDashBoardTotalTeacher2Layout = new javax.swing.GroupLayout(teacherDashBoardTotalTeacher2);
        teacherDashBoardTotalTeacher2.setLayout(teacherDashBoardTotalTeacher2Layout);
        teacherDashBoardTotalTeacher2Layout.setHorizontalGroup(
            teacherDashBoardTotalTeacher2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherDashBoardTotalTeacher2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(teacherValue2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teacherIcon2)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(teacherDashBoardTotalTeacher2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalTeacher2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        teacherDashBoardTotalTeacher2Layout.setVerticalGroup(
            teacherDashBoardTotalTeacher2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherDashBoardTotalTeacher2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(totalTeacher2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(teacherDashBoardTotalTeacher2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teacherValue2)
                    .addComponent(teacherIcon2))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        teacherDashBoardTotalCourse2.setBackground(new java.awt.Color(107, 201, 46));
        teacherDashBoardTotalCourse2.setPreferredSize(new java.awt.Dimension(155, 130));

        totalCourse2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        totalCourse2.setForeground(new java.awt.Color(255, 255, 255));
        totalCourse2.setText("Total Course");

        courseValue2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        courseValue2.setForeground(new java.awt.Color(255, 255, 255));
        courseValue2.setText("10");

        courseIcon2.setForeground(new java.awt.Color(255, 255, 255));
        courseIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swing/Rectangle 8.png"))); // NOI18N

        javax.swing.GroupLayout teacherDashBoardTotalCourse2Layout = new javax.swing.GroupLayout(teacherDashBoardTotalCourse2);
        teacherDashBoardTotalCourse2.setLayout(teacherDashBoardTotalCourse2Layout);
        teacherDashBoardTotalCourse2Layout.setHorizontalGroup(
            teacherDashBoardTotalCourse2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherDashBoardTotalCourse2Layout.createSequentialGroup()
                .addGroup(teacherDashBoardTotalCourse2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(teacherDashBoardTotalCourse2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(courseValue2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(courseIcon2))
                    .addGroup(teacherDashBoardTotalCourse2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(totalCourse2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        teacherDashBoardTotalCourse2Layout.setVerticalGroup(
            teacherDashBoardTotalCourse2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherDashBoardTotalCourse2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(totalCourse2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(teacherDashBoardTotalCourse2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(courseValue2)
                    .addComponent(courseIcon2))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout teacherDashboard2Layout = new javax.swing.GroupLayout(teacherDashboard2);
        teacherDashboard2.setLayout(teacherDashboard2Layout);
        teacherDashboard2Layout.setHorizontalGroup(
            teacherDashboard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherDashboard2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(teacherDaskBoardTotalStd2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(teacherDashBoardTotalTeacher2, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addComponent(teacherDashBoardTotalCourse2, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teacherDashboard2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(teacherDashBoardTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(teacherDashboard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teacherDashBoardRole)
                    .addComponent(teacherDashBoardUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        teacherDashboard2Layout.setVerticalGroup(
            teacherDashboard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherDashboard2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(teacherDashboard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherDashBoardTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherDashBoardUserName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teacherDashBoardRole, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200)
                .addGroup(teacherDashboard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teacherDaskBoardTotalStd2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherDashBoardTotalTeacher2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherDashBoardTotalCourse2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(200, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", teacherDashboard2);

        teacherCoourse2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("course");

        javax.swing.GroupLayout teacherCoourse2Layout = new javax.swing.GroupLayout(teacherCoourse2);
        teacherCoourse2.setLayout(teacherCoourse2Layout);
        teacherCoourse2Layout.setHorizontalGroup(
            teacherCoourse2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherCoourse2Layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jLabel2)
                .addContainerGap(259, Short.MAX_VALUE))
        );
        teacherCoourse2Layout.setVerticalGroup(
            teacherCoourse2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherCoourse2Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel2)
                .addContainerGap(405, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", teacherCoourse2);

        teacherTutors2.setBackground(new java.awt.Color(255, 255, 255));

        teacherTutorsTable2.setBackground(new java.awt.Color(255, 255, 255));

        tutorsTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"saurabh chaudhary", "saurabha@gmail.com", "9812345678", "Bit"},
                {"ronit shreatha", "ronit@gmail.com", "98213456", "Bit"}
            },
            new String [] {
                "Name", "Email", "Phone", "Course"
            }
        ));
        teacherTutorsTable2.setViewportView(tutorsTable2);

        teacherTutor2.setBackground(new java.awt.Color(255, 255, 255));
        teacherTutor2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tutor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14), new java.awt.Color(107, 201, 46))); // NOI18N
        teacherTutor2.setForeground(new java.awt.Color(107, 201, 46));

        teacherTutorName2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        teacherTutorName2.setForeground(new java.awt.Color(107, 201, 46));
        teacherTutorName2.setText("Name");

        teacherTutorNameInput.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        teacherTutorNameInput.setForeground(new java.awt.Color(107, 201, 46));
        teacherTutorNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherTutorNameInputActionPerformed(evt);
            }
        });

        teacherTutorEmail2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        teacherTutorEmail2.setForeground(new java.awt.Color(107, 201, 46));
        teacherTutorEmail2.setText("Email");

        teacherTutorEmailInput.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        teacherTutorEmailInput.setForeground(new java.awt.Color(107, 201, 46));
        teacherTutorEmailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherTutorEmailInputActionPerformed(evt);
            }
        });

        teacherTutorPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        teacherTutorPhone.setForeground(new java.awt.Color(107, 201, 46));
        teacherTutorPhone.setText("Phone");

        teacherTutorCourse.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        teacherTutorCourse.setForeground(new java.awt.Color(107, 201, 46));
        teacherTutorCourse.setText("Course");

        teacherTutorCourseInput.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        teacherTutorCourseInput.setForeground(new java.awt.Color(107, 201, 46));
        teacherTutorCourseInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherTutorCourseInputActionPerformed(evt);
            }
        });

        teacherTutorPhoneInput.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        teacherTutorPhoneInput.setForeground(new java.awt.Color(107, 201, 46));
        teacherTutorPhoneInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherTutorPhoneInputActionPerformed(evt);
            }
        });

        teacherTutorAdd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        teacherTutorAdd.setForeground(new java.awt.Color(107, 201, 46));
        teacherTutorAdd.setText("Add");

        teacherTutorDelect.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        teacherTutorDelect.setForeground(new java.awt.Color(107, 201, 46));
        teacherTutorDelect.setText("Delete");

        teacherTutorUpdate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        teacherTutorUpdate.setForeground(new java.awt.Color(107, 201, 46));
        teacherTutorUpdate.setText("Update");

        teacherTutorSave.setText("Save");
        teacherTutorSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherTutorSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout teacherTutor2Layout = new javax.swing.GroupLayout(teacherTutor2);
        teacherTutor2.setLayout(teacherTutor2Layout);
        teacherTutor2Layout.setHorizontalGroup(
            teacherTutor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherTutor2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(teacherTutor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(teacherTutor2Layout.createSequentialGroup()
                        .addComponent(teacherTutorSave, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(teacherTutor2Layout.createSequentialGroup()
                        .addGroup(teacherTutor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(teacherTutor2Layout.createSequentialGroup()
                                .addGroup(teacherTutor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(teacherTutorNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(teacherTutorName2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(teacherTutorPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(teacherTutorPhoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(teacherTutor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(teacherTutorEmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(teacherTutorEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(teacherTutorCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(teacherTutorCourseInput, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teacherTutor2Layout.createSequentialGroup()
                                .addComponent(teacherTutorAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(teacherTutorDelect, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(teacherTutorUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30))))
        );

        teacherTutor2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {teacherTutorEmailInput, teacherTutorName2, teacherTutorNameInput});

        teacherTutor2Layout.setVerticalGroup(
            teacherTutor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherTutor2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(teacherTutor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherTutorName2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherTutorEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(teacherTutor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherTutorNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherTutorEmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(teacherTutor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherTutorCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherTutorPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(teacherTutor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(teacherTutorCourseInput, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(teacherTutorPhoneInput))
                .addGap(32, 32, 32)
                .addGroup(teacherTutor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherTutorAdd)
                    .addComponent(teacherTutorDelect)
                    .addComponent(teacherTutorUpdate))
                .addGap(18, 18, 18)
                .addComponent(teacherTutorSave)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        teacherTutor2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {teacherTutorEmailInput, teacherTutorName2, teacherTutorNameInput});

        teacherTutor2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {teacherTutorAdd, teacherTutorDelect, teacherTutorUpdate});

        javax.swing.GroupLayout teacherTutors2Layout = new javax.swing.GroupLayout(teacherTutors2);
        teacherTutors2.setLayout(teacherTutors2Layout);
        teacherTutors2Layout.setHorizontalGroup(
            teacherTutors2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherTutors2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(teacherTutors2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(teacherTutor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(teacherTutorsTable2, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        teacherTutors2Layout.setVerticalGroup(
            teacherTutors2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherTutors2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teacherTutor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(teacherTutorsTable2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        jTabbedPane1.addTab("tab3", teacherTutors2);

        teacherEdit2.setBackground(new java.awt.Color(255, 255, 255));

        teacherEditTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        teacherEditTitle.setForeground(new java.awt.Color(107, 201, 46));
        teacherEditTitle.setText("Student Information");

        teacherEditIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Swing/icons8-student-registration-50.png"))); // NOI18N

        teacherEditFirstName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        teacherEditFirstName.setForeground(new java.awt.Color(107, 201, 46));
        teacherEditFirstName.setText("FirstName");

        teacherEditLastName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        teacherEditLastName.setForeground(new java.awt.Color(107, 201, 46));
        teacherEditLastName.setText("LastName");

        teacherEditFirstNameUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        teacherEditFirstNameUser.setForeground(new java.awt.Color(107, 201, 46));
        teacherEditFirstNameUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        teacherEditLastNameUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        teacherEditLastNameUser.setForeground(new java.awt.Color(107, 201, 46));
        teacherEditLastNameUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        teacherEditEmail.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        teacherEditEmail.setForeground(new java.awt.Color(107, 201, 46));
        teacherEditEmail.setText("Email");

        teacherEditPassword.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        teacherEditPassword.setForeground(new java.awt.Color(107, 201, 46));
        teacherEditPassword.setText("Password");

        teacherEditEmailUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        teacherEditEmailUser.setForeground(new java.awt.Color(107, 201, 46));
        teacherEditEmailUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        teacherEditPasswordUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        teacherEditPasswordUser.setForeground(new java.awt.Color(107, 201, 46));
        teacherEditPasswordUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        stdEditUserName.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        stdEditUserName.setForeground(new java.awt.Color(107, 201, 46));
        stdEditUserName.setText("UserName");

        teacherEditMobileNo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        teacherEditMobileNo.setForeground(new java.awt.Color(107, 201, 46));
        teacherEditMobileNo.setText("MobileNo");

        teacherEditUserNameInput.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        teacherEditUserNameInput.setForeground(new java.awt.Color(107, 201, 46));
        teacherEditUserNameInput.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        teacherEditUserNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherEditUserNameInputActionPerformed(evt);
            }
        });

        teacherEditMobileNoUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        teacherEditMobileNoUser.setForeground(new java.awt.Color(107, 201, 46));
        teacherEditMobileNoUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        stdEditBtn.setBackground(new java.awt.Color(107, 201, 46));
        stdEditBtn.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        stdEditBtn.setForeground(new java.awt.Color(255, 255, 255));
        stdEditBtn.setText("Submit");
        stdEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdEditBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout teacherEdit2Layout = new javax.swing.GroupLayout(teacherEdit2);
        teacherEdit2.setLayout(teacherEdit2Layout);
        teacherEdit2Layout.setHorizontalGroup(
            teacherEdit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherEdit2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(teacherEdit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teacherEdit2Layout.createSequentialGroup()
                        .addGroup(teacherEdit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(teacherEdit2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(teacherEditIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(teacherEdit2Layout.createSequentialGroup()
                                .addComponent(teacherEditFirstNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(40, 40, 40))
                    .addGroup(teacherEdit2Layout.createSequentialGroup()
                        .addGroup(teacherEdit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teacherEditFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(teacherEdit2Layout.createSequentialGroup()
                                .addGroup(teacherEdit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(teacherEditEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(teacherEditEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stdEditUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(teacherEditUserNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addGroup(teacherEdit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(teacherEditPasswordUser, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(teacherEditPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(teacherEditMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(teacherEditMobileNoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(teacherEditLastNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(teacherEditLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(teacherEditTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(47, Short.MAX_VALUE))))
            .addGroup(teacherEdit2Layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(stdEditBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        teacherEdit2Layout.setVerticalGroup(
            teacherEdit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherEdit2Layout.createSequentialGroup()
                .addGroup(teacherEdit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(teacherEdit2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(teacherEditTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(teacherEdit2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(teacherEditIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(teacherEdit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherEditFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherEditLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(teacherEdit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherEditFirstNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherEditLastNameUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(teacherEdit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherEditEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherEditPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(teacherEdit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherEditEmailUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherEditPasswordUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(teacherEdit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdEditUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherEditMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(teacherEdit2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherEditUserNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherEditMobileNoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(stdEditBtn)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", teacherEdit2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, -36, 550, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void teacherCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherCourseActionPerformed
        // TODO add your handling code here:
        teacherCourse.setBorderPainted(false);
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_teacherCourseActionPerformed

    private void teacherTutorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherTutorsActionPerformed
        // TODO add your handling code here:
           teacherTutors.setBorderPainted(false);
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_teacherTutorsActionPerformed

    private void teacherEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherEditActionPerformed
        // TODO add your handling code here
         teacherEdit.setBorderPainted(false);
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_teacherEditActionPerformed

    private void teacherLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherLogOutMouseClicked
        // TODO add your handling code here:
        Login student = new Login();
        student.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_teacherLogOutMouseClicked

    private void teacherLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherLogOutActionPerformed
        // TODO add your handling code here:
            // TODO add your handling code here
        teacherLogOut.setBorderPainted(false);
    }//GEN-LAST:event_teacherLogOutActionPerformed

    private void teacherDashBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherDashBoardActionPerformed
        // TODO add your handling code here:
         teacherDashBoard.setBorderPainted(false);
        jTabbedPane1.setSelectedIndex(0);
        // studentDashBoard.setBorderPainted(false);

    }//GEN-LAST:event_teacherDashBoardActionPerformed

    private void teacherEditUserNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherEditUserNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherEditUserNameInputActionPerformed

    private void stdEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdEditBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdEditBtnActionPerformed

    private void teacherTutorNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherTutorNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherTutorNameInputActionPerformed

    private void teacherTutorEmailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherTutorEmailInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherTutorEmailInputActionPerformed

    private void teacherTutorCourseInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherTutorCourseInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherTutorCourseInputActionPerformed

    private void teacherTutorPhoneInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherTutorPhoneInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherTutorPhoneInputActionPerformed

    private void teacherTutorSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherTutorSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherTutorSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel courseIcon2;
    private javax.swing.JLabel courseValue2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton stdEditBtn;
    private javax.swing.JLabel stdEditUserName;
    private javax.swing.JLabel stdIcon2;
    private javax.swing.JLabel stdValue2;
    private javax.swing.JPanel teacherCoourse2;
    private javax.swing.JButton teacherCourse;
    private javax.swing.JButton teacherDashBoard;
    private javax.swing.JLabel teacherDashBoardRole;
    private javax.swing.JLabel teacherDashBoardTittle;
    private javax.swing.JPanel teacherDashBoardTotalCourse2;
    private javax.swing.JPanel teacherDashBoardTotalTeacher2;
    private javax.swing.JLabel teacherDashBoardUserName;
    private javax.swing.JPanel teacherDashboard2;
    private javax.swing.JPanel teacherDaskBoardTotalStd2;
    private javax.swing.JButton teacherEdit;
    private javax.swing.JPanel teacherEdit2;
    private javax.swing.JLabel teacherEditEmail;
    private javax.swing.JTextField teacherEditEmailUser;
    private javax.swing.JLabel teacherEditFirstName;
    private javax.swing.JTextField teacherEditFirstNameUser;
    private javax.swing.JLabel teacherEditIcon;
    private javax.swing.JLabel teacherEditLastName;
    private javax.swing.JTextField teacherEditLastNameUser;
    private javax.swing.JLabel teacherEditMobileNo;
    private javax.swing.JTextField teacherEditMobileNoUser;
    private javax.swing.JLabel teacherEditPassword;
    private javax.swing.JTextField teacherEditPasswordUser;
    private javax.swing.JLabel teacherEditTitle;
    private javax.swing.JTextField teacherEditUserNameInput;
    private javax.swing.JLabel teacherIcon;
    private javax.swing.JLabel teacherIcon2;
    private javax.swing.JButton teacherLogOut;
    private javax.swing.JPanel teacherTutor2;
    private javax.swing.JButton teacherTutorAdd;
    private javax.swing.JLabel teacherTutorCourse;
    private javax.swing.JTextField teacherTutorCourseInput;
    private javax.swing.JButton teacherTutorDelect;
    private javax.swing.JLabel teacherTutorEmail2;
    private javax.swing.JTextField teacherTutorEmailInput;
    private javax.swing.JLabel teacherTutorName2;
    private javax.swing.JTextField teacherTutorNameInput;
    private javax.swing.JLabel teacherTutorPhone;
    private javax.swing.JTextField teacherTutorPhoneInput;
    private javax.swing.JButton teacherTutorSave;
    private javax.swing.JButton teacherTutorUpdate;
    private javax.swing.JButton teacherTutors;
    private javax.swing.JPanel teacherTutors2;
    private javax.swing.JScrollPane teacherTutorsTable2;
    private javax.swing.JLabel teacherValue2;
    private javax.swing.JLabel totalCourse2;
    private javax.swing.JLabel totalStd2;
    private javax.swing.JLabel totalTeacher2;
    private javax.swing.JTable tutorsTable2;
    // End of variables declaration//GEN-END:variables
}
